version: "3.9"
services:
  #front-end:
  #  build: ./adeus-filas/
  #  ports:
  #    - "3000:80"
  #  restart: always
  back-end:
    build: ./exemplo-mongo-api/
    ports:
      - "3001:3001"
    restart: always
  mongodb:
    image: mongo
    environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: pessoas
    ports:
      - "27017:27017"
    restart: always
