FROM node:18

# Create app directory
WORKDIR adeus-filas-api/usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY adeus-filas-api/package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --omit=dev

# Bundle app source
COPY ./adeus-filas-api .

EXPOSE 8080
CMD [ "node", "index.js" ]
